### ISSUE TITLE
Crashes upon boot

### ISSUE THREAD

**Issue by coolcool247** [sereneblue/imgr3ds#1]
Hi, I installed imgr3ds and it crashed when i tried to boot it through the Homebrew menu. I have a New 3DS XL on the latest version of luma3DS.
![IMG_20200626_174655228](https://user-images.githubusercontent.com/67486364/85903741-1b2be500-b7d5-11ea-8289-6ddbbe8ad4d4.jpg)

**Comment by sereneblue** [comment]
Hi @coolcool247,

I don't work with 3DS homebrew these days so I'm not sure if I can help you. I did some research and I don't think this issue is caused because of imgr3DS. [This](https://gbatemp.net/threads/arm11-exception-occured-prefetch-abort-kernel-panic.532529/) thread may be helpful. Please note, this homebrew application was made for learning purposes. Using the browser should give you a better imgur experience.

**Comment by coolcool247** [comment]
Well, thanks!
